### ISSUE TITLE
Increase and decrease volume only incrementing one 'level'

### ISSUE THREAD

**Issue by eejd** [Doraemoe/Spotify-Plugin-for-Quicksilver#5] opened 2015-09-14 15:03 UTC
Recently (an update to Spotify caused?) my Quicksilver Spotify trigger controls for the application volume to only toggle between two values. If I set the volume to ~80% and then press the 'Increase Volume' trigger key-combo, the volume jumps down to about ~40% and if I press down if drops to ~35%. Repeated 'Increase Volume' requests simply have no effect. Basically, the increase and decrease volume triggers toggle between what appear to be two volume levels.

**Comment by Doraemoe** [comment] 2015-09-16 08:03
Applescript for volume in Spotify seems broken, I will contact Spotify support to see if they can do anything

**Comment by Doraemoe** [comment] 2015-09-22 06:06
According to this thread: https://community.spotify.com/t5/Help-Desktop-Mac/AppleScript-volume-issue/td-p/1199021

The problem is caused because the Spotify no longer updates the volume number in real time. This cannot be fixed in my end, hope they could fix this in their next update.

**Comment by Doraemoe** [comment] 2015-09-22 12:53
New version 1.0.14.124 fixed this problem.

**Closed as completed by Doraemoe** 2015-09-22 12:53 UTC

**Comment by eejd** [comment] 2015-10-15 16:32
Thanks
